services:
  - type: web
    name: whatsapp-bot
    env: node
    plan: free
    buildCommand: "npm install && npx puppeteer browsers install chrome"
    startCommand: "node index.js"
    autoDeploy: true

    envVars:
      - key: PORT
        value: "3000"

    disk:
      name: whatsapp-session
      mountPath: /data
      sizeGB: 1
      